language: node_js
git:
  depth: 1
node_js:
- '8'
cache:
  directories:
  - node_modules
install:
  - npm install -g now@11.3.8
branches:
  only:
   - master
   - /^v\d+\.\d+\.\d+$/
notifications:
  email: false
script:
  - bash ./deploy.sh
