language: node_js
git:
  depth: 1
node_js:
- '8'
cache:
  directories:
  - node_modules
install: npm install -g now@7.4.0
branches:
  only:
   - master
   - feat/travis-dev
   - /^v\d+\.\d+\.\d+$/
notifications:
  email: false
script:
  - bash ./deploy-env.sh $TRAVIS_BRANCH $NOW_TOKEN $DATO_API_TOKEN
